[package]
name = "constellation-server"
version = "1.11.0"
description = "Pluggable authoritative DNS server. Entries can be added & removed from an HTTP REST API."
readme = "README.md"
license = "MPL-2.0"
edition = "2018"
homepage = "https://github.com/valeriansaliou/constellation"
repository = "https://github.com/valeriansaliou/constellation.git"
keywords = ["dns", "api"]
categories = ["web-programming"]
authors = ["Valerian Saliou <valerian@valeriansaliou.name>"]

[badges]
travis-ci = { repository = "valeriansaliou/constellation", branch = "master" }
coveralls = { repository = "valeriansaliou/constellation", branch = "master", service = "github" }

[[bin]]
name = "constellation"
path = "src/main.rs"
doc = false

[dependencies]
log = { version = "0.4", features = ["std"] }
toml = "0.5"
clap = { version = "2.33", default-features = false }
lazy_static = "1.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url_serde = { version = "0.2", default-features = false }
base64 = "0.12"
regex = "1.3"
r2d2 = "0.8"
r2d2_redis = "0.13"
redis = "0.16"
rocket = { version = "0.4", default-features = false }
rocket_contrib = { version = "0.4", features = ["json"], default-features = false }
trust-dns-proto = { version = "*", default-features = false, features = ["tokio-runtime", "dnssec-ring", "serde"]}
trust-dns-server = { version = "*", default-features = false, features = ["dns-over-https-rustls", "dns-over-rustls", "dnssec-ring"] }
rand = "0.7"
farmhash = "1.1"
http_req = { version = "0.6", features = ["rust-tls"], default-features = false }
maxminddb = "0.13"
tempfile = "3.1"
flate2 = "1.0"
tar = "0.4"
tokio = "0.2"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true

[profile.release]
opt-level = "s"
lto = true
debug = false
debug-assertions = false
